---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items:
    - g_home

- name: ensure ~/bin exists
  ansible.builtin.file:
    path: "{{ g_home }}/bin"
    state: directory
    mode: u=rwx,g=,o=

- name: deploy personal-ansible script
  ansible.builtin.template:
    src: personal-ansible.bash.j2
    dest: "{{ g_home }}/bin/personal-ansible.bash"
    mode: u=rx,g=r,o=
