---
- name: Check mandatory variables are defined
  assert:
    that: lookup('vars', item) or true
  with_items:
    - g_home
    - remote_tempdir
    - sdk

- name: set temp dest name
  set_fact:
    temp_dest: "{{ remote_tempdir.path }}/dotnet-sdk-{{ sdk.ver }}"

- name: download SDK
  get_url:
    url: "{{ sdk.url }}"
    checksum: "{{ sdk.checksum }}"
    dest: "{{ temp_dest }}.tgz"
    timeout: 30
  changed_when: false # Will always be changed

- name: make temp output dir
  file:
    path: "{{ temp_dest }}"
    state: directory
    mode: u=rwx,g=,o=
  changed_when: false # Will always be changed

- name: unarchive dotnet
  unarchive:
    src: "{{ temp_dest }}.tgz"
    dest: "{{ temp_dest }}"
    remote_src: true
  changed_when: false # Will always be changed

- name: merge files into dotnet_install_dir
  command: cp -rT {{ temp_dest }}/ {{ dotnet_install_dir }}/
  changed_when: true # mark as changed if run
