---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items:
    - env_cargo_home
    - env_rustup_home

- name: check for existing install
  ansible.builtin.stat:
    path: "{{ env_cargo_home }}"
  register: r_existing_cargo_home

- name: Install rust
  ansible.builtin.shell: >
    set -euxo pipefail
    curl https://sh.rustup.rs |
    CARGO_HOME={{ env_cargo_home | quote }}
    RUSTUP_HOME={{ env_rustup_home | quote }}
    sh -s -- --quiet -y --no-modify-path
  when: not r_existing_cargo_home.stat.exists
  changed_when: true

# nightly

- name: Install nightly toolchain
  ansible.builtin.shell: >
    set -euxo pipefail
    CARGO_HOME={{ env_cargo_home | quote }}
    RUSTUP_HOME={{ env_rustup_home | quote }}
    {{ env_cargo_home | quote }}/bin/rustup toolchain install nightly
  register: r_rustup_nightly
  changed_when: '"updated" in r_rustup_nightly.stdout'

- name: rustup update
  ansible.builtin.shell: >
    CARGO_HOME={{ env_cargo_home | quote }}
    RUSTUP_HOME={{ env_rustup_home | quote }}
    {{ env_cargo_home | quote }}/bin/rustup update
  register: r_rustup_update
  changed_when: '"updated" in r_rustup_update.stdout'
