---
ci:
  skip: [ansible-lint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/rkm/pre-commit-nocommit
    rev: "v1.0.0"
    hooks:
      - id: nocommit
        exclude: |
          (?x)^(
              .pre-commit-config.yaml
          )
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.1.0"
    hooks:
      - id: codespell
        args:
          [
            --ignore-words,
            .meta/codespell-ignores,
            --exclude-file,
            .meta/codespell-excludes,
            --ignore-regex,
            '\Whttps?://\S*',
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.0"
    hooks:
      - id: prettier
        args: [--config, .meta/prettierrc.yaml]
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.26.3"
    hooks:
      - id: yamllint
        args: [-c, .meta/yamllint.yaml]
  # TODO(rkm 2021-10-31) Enable
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: "v0.7.2.1"
  #   hooks:
  #     - id: shellcheck
  - repo: https://github.com/ansible/ansible-lint.git
    rev: "v5.2.1"
    hooks:
      - id: ansible-lint
        args: [-c, .meta/ansible-lint.yaml]
        additional_dependencies:
          - .[community]
