---
ci:
  skip: [ansible-lint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/rkm/pre-commit-nocommit
    rev: "v1.0.0"
    hooks:
      - id: nocommit
        exclude: |
          (?x)^(
              .pre-commit-config.yaml
          )
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.5"
    hooks:
      - id: codespell
        args:
          [
            --ignore-words,
            .meta/codespell-ignores,
            --exclude-file,
            .meta/codespell-excludes,
            --ignore-regex,
            '\Whttps?://\S*',
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        args: [--config, .meta/prettierrc.yaml]
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint
        args: [-c, .meta/yamllint.yaml]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.9.0.5"
    hooks:
      - id: shellcheck
  - repo: https://github.com/ansible/ansible-lint.git
    rev: "v6.17.2"
    hooks:
      - id: ansible-lint
        args: [-c, .meta/ansible-lint.yaml]
