---
- name: setup
  hosts: all
  tags: [always]
  tasks:
    - name: create tempdir
      delegate_to: localhost
      tempfile:
        state: directory
      register: tempdir
      changed_when: false

- name: Run global roles
  hosts: all
  pre_tasks:
    - name: end_play if not g_global_install
      meta: end_play
      when: not g_global_install | bool
  roles:
    - role: packages
      tags: [packages]

- name: install dotfiles
  hosts: all
  tags: [dotfiles]
  roles:
    - dotfiles

- name: cleanup
  hosts: all
  tags: [always, cleanup]
  tasks:
    - name: find temp dirs
      delegate_to: localhost
      find:
        paths: /tmp
        file_type: directory
        recurse: false
        patterns: "ansible.*"
      register: temp_paths
    - name: delete temp dirs
      delegate_to: localhost
      file:
        path: "{{ item.path }}"
        # TODO(rkm 2021-10-31) This can fail if other users have ansible temp dirs
        state: absent
      with_items: "{{ temp_paths.files }}"
      changed_when: false
