---
- name: update package cache
  become: true
  package:
    update_cache: yes
  when: g_packages_role | bool
  changed_when: false # could be changed

- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest
  when: g_packages_role | bool

- name: Install RHEL packages
  become: true
  package:
    name: "{{ packages_rhel }}"
    state: latest
  when: (g_packages_role | bool) and ansible_os_family == 'RedHat'
