---
- name: update package cache
  become: true
  package:
    update_cache: yes
  when: g_packages_role | bool
  changed_when: false # could be changed

- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: present
  when: g_packages_role | bool
