---
- name: Check mandatory variables are defined
  assert:
    that: lookup('vars', item) or true
  with_items:
    - g_packages_role

- name: install epel in rhel
  become: true
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: update package cache
  become: true
  package:
    update_cache: yes
  when: g_packages_role | bool
  changed_when: false # could be changed

- name: upgrade all packages
  become: true
  yum:
    name: "*"
    state: latest # noqa package-latest
  when: g_packages_role | bool

- name: Install packages
  become: true
  package:
    name: "{{ packages }}"
    state: latest # noqa package-latest
  when: g_packages_role | bool

- name: RHEL-specific packages
  include_tasks: rhel.yaml
  when: (g_packages_role | bool) and ansible_os_family == 'RedHat'

- name: Ubuntu-specific packages
  include_tasks: ubuntu.yaml
  when: (g_packages_role | bool) and ansible_distribution == "Ubuntu"
