---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items: []

- name: install epel in rhel
  become: true
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: update package cache
  become: true
  ansible.builtin.package:
    update_cache: true
  changed_when: false # could be changed

- name: upgrade all packages
  become: true
  ansible.builtin.package:
    name: "*"
    state: latest # noqa package-latest

- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ packages }}"
    state: latest # noqa package-latest

- name: RHEL-specific packages
  include_tasks: rhel.yaml
  when: ansible_os_family == 'RedHat'

- name: Ubuntu-specific packages
  include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
