---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items:
    - packages_rhel
    - removes_rhel

- name: install specified RHEL packages
  become: true
  package:
    name: "{{ packages_rhel }}"
    state: latest # noqa package-latest

- name: remove specified rhel packages
  become: true
  package:
    name: "{{ removes_rhel }}"
    state: absent
    autoremove: true

- name: check for cockpit motd
  stat:
    path: /etc/motd.d/cockpit
  register: cockpit_stat_result

- name: mask cockpit motd if exists
  become: true
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/motd.d/cockpit
    state: link
  when: cockpit_stat_result.stat.exists
