---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('ansible.builtin.vars', item) or true
  with_items:
    - packages_rhel_{{ ansible_distribution_major_version }}
    - removes_rhel_{{ ansible_distribution_major_version }}

- name: install specified RHEL packages
  become: true
  ansible.builtin.package:
    name: "{{ lookup('ansible.builtin.vars', 'packages_rhel_' + ansible_distribution_major_version) }}"
    state: latest # noqa package-latest

- name: remove specified RHEL packages
  become: true
  ansible.builtin.package:
    name: "{{ lookup('ansible.builtin.vars', 'removes_rhel_' + ansible_distribution_major_version) }}"
    state: absent
    autoremove: true

- name: check for cockpit motd
  ansible.builtin.stat:
    path: /etc/motd.d/cockpit
  register: cockpit_stat_result

- name: mask cockpit motd if exists
  become: true
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/motd.d/cockpit
    state: link
  when: cockpit_stat_result.stat.exists
