---
- name: download dotfiles
  delegate_to: localhost
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: unarchive dotfiles
  delegate_to: localhost
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: true
    list_files: true
  changed_when: false # Will always be changed
  register: archive_contents

- name: create combined .gitconfig
  delegate_to: localhost
  shell: |
    set -o pipefail
    cat \
      "{{ item }}/common/gitconfig" \
      "{{ item }}/linux/config/git/config" \
    | tee "{{ item }}/linux/config/git/config" \
    > /dev/null
  changed_when: false # Will always be changed
  with_items:
    - "{{ tempdir.path }}/{{ archive_contents.files[0] }}"

- name: delete old dotfiles VERSION file
  file:
    dest: "{{ g_home }}/.config/VERSION"
    state: absent
  changed_when: false # will normally be changed

- name: deploy dotfiles
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    checksum: true
    times: false
    dirs: true
    delete: true
  with_items:
    - src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/config/"
      dest: "{{ g_home }}/.config"
    - src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/profile"
      dest: "{{ g_home }}/.profile"
  register: sync_result

- name: register temp fact
  set_fact:
    deleted_items: "{{ sync_result.results | selectattr('msg', 'contains', 'deleting') }}"

- name: debug deleted files
  debug:
    var: deleted_items
  when: deleted_items | length
  changed_when: true # changed if run

- name: register dotfiles dirname
  find:
    paths: "{{ tempdir.path }}"
    file_type: directory
    recurse: false
    pattern: rkm-dotfiles-*
  register: dotfiles_dir_name

- name: assert one file matched
  assert:
    that: dotfiles_dir_name.files | length == 1

- name: write dotfiles version
  copy:
    content: "{{ dotfiles_dir_name.files[0].path.split('-')[2] }}\n"
    dest: "{{ g_home }}/.config/VERSION"
  changed_when: false # will always be changed
