---
- name: download dotfiles
  delegate_to: localhost
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: unarchive dotfiles
  delegate_to: localhost
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: true
    list_files: true
  changed_when: false # Will always be changed
  register: archive_contents

- name: create combined .gitconfig
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    set -o pipefail
    cat \
      "{{ item }}/common/gitconfig" \
      "{{ item }}/linux/config/git/config" \
    | tee "{{ item }}/linux/config/git/config" \
    > /dev/null
  changed_when: false # Will always be changed
  with_items:
    - "{{ tempdir.path }}/{{ archive_contents.files[0] }}"

- name: delete old dotfiles VERSION file
  file:
    dest: "{{ g_home }}/.config/VERSION"
    state: absent
  changed_when: false # will normally be changed

- name: deploy dotfiles
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    archive: false
    checksum: true
    times: false
    delete: true
    recursive: true
  with_items:
    - src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/config/"
      dest: "{{ g_home }}/.config"
    - src: "{{ tempdir.path }}/{{ archive_contents.files[0] }}/linux/profile"
      dest: "{{ g_home }}/.profile"
  register: sync_result

- name: debug changed files
  debug:
    msg: "{{ sync_result.results | map(attribute='msg') }}"
  when: sync_result.changed
  changed_when: true # will always be changed

- name: temp ls
  delegate_to: localhost
  command: ls -l /tmp
  changed_when: false

- name: register dotfiles dirname
  delegate_to: localhost
  find:
    paths: "{{ tempdir.path }}"
    file_type: directory
    recurse: false
    pattern: rkm-dotfiles-*
  register: dotfiles_dir_name

- name: assert one file matched
  assert:
    that: dotfiles_dir_name.files | length == 1

- name: write dotfiles version
  copy:
    content: "{{ dotfiles_dir_name.files[0].path.split('-')[2] }}\n"
    dest: "{{ g_home }}/.config/VERSION"
    mode: u=r,g=r,o=
  changed_when: false # will always be changed
