---
- name: download dotfiles
  delegate_to: localhost
  get_url:
    url: https://api.github.com/repos/rkm/dotfiles/tarball
    dest: "{{ tempdir.path }}/dotfiles.tgz"
  changed_when: false # Will always be changed

- name: unarchive dotfiles
  delegate_to: localhost
  unarchive:
    src: "{{ tempdir.path }}/dotfiles.tgz"
    dest: "{{ tempdir.path }}"
    remote_src: true
    list_files: true
  changed_when: false # Will always be changed
  register: archive_contents

- name: register tmp dotfiles path
  set_fact:
    tmp_dotfiles_path: "{{ tempdir.path }}/{{ archive_contents.files[0] }}"

- name: create combined .gitconfig
  delegate_to: localhost
  args:
    executable: /bin/bash
  shell: |
    set -euxo pipefail
    cat \
      "{{ tmp_dotfiles_path }}/common/gitconfig" \
      "{{ tmp_dotfiles_path }}/linux/config/git/config" \
    > "{{ tempdir.path }}/gitconfig"
    mv \
      "{{ tempdir.path }}/gitconfig" \
      "{{ tmp_dotfiles_path }}/linux/config/git/config"
  changed_when: false # Will always be changed

- name: delete old dotfiles VERSION file
  file:
    dest: "{{ g_home }}/.config/VERSION"
    state: absent
  changed_when: false # will normally be changed

# TODO(rkm 2021-11-01) rsync --backup arg
- name: deploy dotfiles
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    archive: false
    checksum: true
    times: false
    delete: true
    recursive: true
  with_items:
    - src: "{{ tmp_dotfiles_path }}/linux/config/"
      dest: "{{ g_home }}/.config"
    - src: "{{ tmp_dotfiles_path }}/linux/profile"
      dest: "{{ g_home }}/.profile"
  register: sync_result

- name: debug changed files
  debug:
    msg: "{{ sync_result.results | map(attribute='msg') }}"
  when: sync_result.changed
  changed_when: true # will always be changed

- name: write dotfiles version
  copy:
    content: "{{ (tmp_dotfiles_path | realpath | basename | split('-'))[2] }}\n"
    dest: "{{ g_home }}/.config/VERSION"
    mode: u=r,g=r,o=
  changed_when: false # will always be changed
