---
# TODO
# - bash-completion # ubuntu
# - dkms
# - htop
# - ImageMagick
# - java-1.8.0-openjdk-devel # ubuntu
# - java-11-openjdk-devel # ubuntu
# - ncdu
# - p7zip
# - perl-Image-ExifTool
# - python36-devel # ubuntu
# - python38-devel # ubuntu

packages:
  - bzip2
  - curl
  - dos2unix
  - figlet
  - gdb
  - git
  - git-lfs
  - graphviz
  - jq
  - make
  - mlocate
  - net-tools
  - nmap
  - patch
  - perl
  - psmisc
  - rsync
  - strace
  - telnet
  - traceroute
  - tree
  - units
  - usbutils
  - vim
  - wget

packages_rhel:
  - bind-utils
  - gcc-c++
  - python39-devel

removes_rhel:
  - PackageKit-command-not-found

packages_ubuntu:
  - bind9-dnsutils
  - g++
  - python3.9
  - python3-distutils

removes_ubuntu:

alternatives:
  - name: python3
    link: /usr/bin/python3
    path: /usr/bin/python3.9
