---
driver:
  name: podman
platforms:
  # TODO(rkm 2021-10-28) Use exact image tags
  - name: rocky-8
    image: docker.io/rockylinux/rockylinux:8
    privileged: true
  - name: ubuntu-20.04
    image: docker.io/ubuntu:latest
    privileged: true
  - name: centos-stream-8
    image: quay.io/centos/centos:latest
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_USER: runner
verifier:
  name: ansible
