---
driver:
  name: podman
platforms:
  - name: rocky-8.4
    image: docker.io/rockylinux/rockylinux:8.4
    privileged: true
  - name: ubuntu-20.04
    image: docker.io/ubuntu:20.04
    privileged: true
  - name: centos-stream-8
    image: quay.io/centos/centos@sha256:338b5d69f1ef6efbf9d57191b36283bb0a29b6f0560a860f0d230caf82490926
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
