---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items: []

- name: install java in rhel
  become: true
  ansible.builtin.package:
    name:
      - java-1.8.0-openjdk
      - java-11-openjdk
    state: present
  when: ansible_os_family == 'RedHat'

- name: install java in debian
  become: true
  ansible.builtin.package:
    name:
      - openjdk-8-jdk
      - openjdk-11-jdk
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install ant
  become: true
  ansible.builtin.package:
    name: ant
    state: present

- name: ensure default maven absent
  become: true
  ansible.builtin.package:
    name: maven
    state: absent
    autoremove: true
  when: ansible_os_family == 'RedHat'

- name: check current maven version
  ansible.builtin.command: "/opt/apache-maven-{{ maven_version }}/bin/mvn --version"
  failed_when: false
  changed_when: false
  register: mvn_result

- name: install maven if required
  include_tasks: maven_install.yaml
  when: mvn_result.rc != 0 or maven_version not in mvn_result.stdout_lines[0]
