---
- name: check mandatory variables are defined
  ansible.builtin.assert:
    that: lookup('vars', item) or true
  with_items:
    - g_home
    - maven_version

- name: register existing maven files
  ansible.builtin.find:
    paths: "/opt/"
    patterns: apache-maven-*
    file_type: directory
  register: maven_files

- name: delete existing maven files
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ maven_files.files }}"

- name: download maven
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    dest: "{{ controller_tempdir.path }}"
    checksum: "sha512:{{ maven_sha512 }}"

- name: unarchive maven
  become: true
  ansible.builtin.unarchive:
    src: "{{ controller_tempdir.path }}/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/opt/"

- name: ensure ~/bin exists
  ansible.builtin.file:
    path: "{{ g_home }}/bin"
    state: directory
    mode: u=rwx,g=,o=

- name: symlink mvn
  ansible.builtin.file:
    src: "/opt/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "{{ g_home }}/bin/mvn"
    state: link
