name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies.
        run: pip install -r requirements.txt
      - name: Run Molecule tests.
        run: molecule test
