name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install test dependencies
        run: pip install -r requirements.txt
      - name: run molecule tests
        run: molecule test
