name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install test dependencies
        run: pip install -r requirements.txt
      - name: install galaxy test dependencies
        run: ansible-galaxy install -r requirements-galaxy.yaml
      - name: run molecule tests
        run: molecule test -- -v
